### ISSUE TITLE
java.io.EOFException: \n in not found inside commandclient.java when working against softap-emulator

### ISSUE THREAD

**Issue by krazineurons** [particle-iot/spark-setup-android#52]
CommandClient.Java line 126 is calling buffer.readUtf8LineStrict, which fails on the response received from the softap-emulator. I don't think there's a need to read the headers from the response as the TCP client doesn't set any headers. Does anyone know why does it read the headers here?

**Comment by jensck** [comment]
`CommandClient` needs to at least _detect_ the headers so it can find and parse the response correctly, because actual Photon hardware _does_ send them.

I'll try to get around to this.  Otherwise, I'd happily accept a patch which gracefully handles both the no headers & with headers cases!

**Comment by jensck** [comment]
Moved: https://github.com/particle-iot/particle-android/issues/59
