### ISSUE TITLE
Refactor icon color tinting to resources

### ISSUE THREAD

**Issue by ppuvanasingam** [particle-iot/spark-setup-android#59]
Hello There,

We have been trying to get our Android app to production, but running into minor issues.

We are using a customized ANDROID device setup library. We were able to change the background from Blue to White by using the customization options/styles. However, we are running into a problem with the icons (such as the wifi, lock, and checkmark) being tinted white and hidden due to the background color being white.

We were able to change some of the icon colors by overriding the layout file, however, once the application is run the activity is tinting the icon color to white (in the row_wifi_scan_result.xml) and tinting the checkmark color to element_text_color in activity_connecting.xml

I also see some FIXME statements indicating, moving the color values to resources. Could we get an update on when it will be updated?

**Comment by CityVibes** [comment]
Hi @ppuvanasingam I'll prioritize this issue for next release, might take few weeks. 
Is there a problem with checkmarks being tinted to element_text_color, it is customizable.

**Comment by ppuvanasingam** [comment]
element_text_color is also used for the Buttons so we would like that to be customizable as well, preferably the same color ID as the others since it makes more sense. Thank you.

**Comment by CityVibes** [comment]
Adding "element_tint_color" to customization.xml, use [setup library 0.5.2](https://github.com/particle-iot/spark-setup-android/releases/tag/v0.5.2).
