### ISSUE TITLE
React Native integration issue

### ISSUE THREAD

**Issue by AbigailMcP** [particle-iot/spark-setup-android#61]
I’m having some trouble integrating the Android SDK with my React Native app.

I’m able to inject an access token using the Cloud SDK and then register a device using the Device Setup Library. However, once setup has finished, I can’t seem to hand back control to RN / return to the “main activity”.

In MainApplication.java I’m initialising the setup library:

```
@Override
  public void onCreate() {
    super.onCreate();
    ...
    ParticleDeviceSetupLibrary.init(this.getApplicationContext(), MainActivity.class);
  }
```

Then in my native module I call:

```
ParticleDeviceSetupLibrary.startDeviceSetup(getReactApplicationContext());
```

I really don’t have much experience writing native code, so any pointers would be much appreciated!

**Comment by CityVibes** [comment]
Looking into it right now.

**Comment by CityVibes** [comment]
@AbigailMcP after setup finished, what happens, does it go somewhere, stuck on the last setup screen?

**Comment by AbigailMcP** [comment]
Hi @CityVibes - thanks for looking into this.

It doesn't get stuck on the last setup screen, it tries to return to the MainActivity. These are the logs:

```
04-05 10:01:09.805 29541-29541/com.statelymobileapp D/NextActivitySelector: Building setup complete activity...
04-05 10:01:09.805 29541-29541/com.statelymobileapp D/NextActivitySelector: Returning setup complete activity
04-05 10:01:09.807 2855-4074/? I/ActivityManager: START u0 {flg=0x34008000 cmp=com.statelymobileapp/.MainActivity} from uid 10099
04-05 10:01:09.835 2855-5652/? W/ActivityManager: Duplicate finish request for ActivityRecord{e83e94f u0 com.statelymobileapp/io.particle.android.sdk.devicesetup.ui.SuccessActivity t44341 f}
04-05 10:01:09.979 29541-29541/com.statelymobileapp D/ReactNative: ReactInstanceManager.detachViewFromInstance()
04-05 10:01:10.002 29541-29541/com.statelymobileapp D/Device set up success: Device 1f0029000c51353432383931 has been configured
04-05 10:01:10.014 29541-29541/com.statelymobileapp D/ReactNative: ReactInstanceManager.attachRootViewToInstance()
04-05 10:01:10.018 29541-29719/com.statelymobileapp I/ReactNativeJS: Running application "StatelyMobileApp" with appParams: {"rootTag":11}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
```

The error I see in my app is:

![screenshot_20180405-100353](https://user-images.githubusercontent.com/18436946/38357049-6d7eee9e-38b9-11e8-8bd8-0716a917826e.png)

Is Particle Device Setup replacing the MainActivity of my app in its entirety? If so, this is different to how the iOS library works, whereby I can easily return to where I left off in React Native.

**Comment by CityVibes** [comment]
@AbigailMcP Unable to reproduce, yet. I'll keep on trying if there's any more info you can provide it would be helpful.
Made an example of running setup in React Native app (Android only) - seems to work fine, check if there's something to borrow from it.

**Comment by AntonPuko** [comment]
@AbigailMcP We had that issue before and finally decide just use js version of particle lib.
@CityVibes You probably can't reproduce because in your example you don't have any `stateful` react-native app. When we return from device setup flow it recreates the activity and drop all the current react-native app state.

**Comment by AbigailMcP** [comment]
Thanks @AntonPuko - I think that's part of the issue. Were you able to kick off the actual device set up wizard with the JS library? Do you have any pointers?

**Comment by AntonPuko** [comment]
We needed only wifi-setup, so I implemented the setup screens by myself. The hardest thing was to make crypto stuff working in react-native.
I do crypto with node-rsa, so here is part of rn-cli config to make it works:
https://github.com/Brewskey/Brewskey.App/blob/v2/react-native-start-with-link.js#L56-L66
crypto service:
https://github.com/Brewskey/Brewskey.App/blob/v2/src/SoftApService.js

The setup flow logic implemented in a mobx-store, its pretty clunky, with redux it can 
be more straightforward probably, but whatever..take a look if it helps:
https://github.com/Brewskey/Brewskey.App/blob/v2/src/stores/WifiSetupStore.js

**Comment by AbigailMcP** [comment]
Thanks @AntonPuko!  🎉 This is really useful - it's given us a load of ideas to go off :)

I do feel like this is still a bug in the library though, due to the recreation of the activity and dropping of state.

**Comment by AntonPuko** [comment]
yeah, agree...Or It can be some flag for main activity in android manifest that change the current behaviour...something like `android:launchMode="singleTop"` ...I just don't know android development at all, so couldn't figure that by myself and all that `android activity` stuff makes my head sick :)))

**Comment by jalada** [comment]
@AntonPuko out of interest is there a reason you used the HTTP SoftAP API instead of the TCP one? Wondering if the TCP one is a little more reliable...

**Comment by AntonPuko** [comment]
Hi, @jalada. Nothing special, just didn't think about TCP way, since it probably needs one more 3rd party lib like `react-native-tcp`, I guess? If you go that way and find any benefits, let me know, please.

**Comment by jensck** [comment]
Moved to: https://github.com/particle-iot/particle-android/issues/57
