### ISSUE TITLE
DexArchiveBuilderException when building

### ISSUE THREAD

**Issue by 7200rpm** [particle-iot/spark-setup-android#62]
Getting an issue when building with the latest 0.5.2 related to dex and "invoke-customs". I have "multiDexEnabled" as true in my defaultconfig. Switching back to 0.4.9 builds with no issues. Not sure if this is a bug or something else in my config. Would appreciate any help!

<img width="696" alt="devicesetupissue" src="https://user-images.githubusercontent.com/9924154/38220758-e1f78a5e-3690-11e8-93aa-84ec650b4be7.PNG">

**Comment by CityVibes** [comment]
@7200rpm Do you target Java8 or 7? Code below should exist in your build.gradle
```
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
```

**Comment by 7200rpm** [comment]
That seemed to fix it! Given that this isn't the default setup, might be worth mentioning.
