### ISSUE TITLE
`Could not find Network for SSID` on Android P

### ISSUE THREAD

**Issue by rduriancik** [particle-iot/spark-setup-android#66]
Hi, we have some issues to claim P1 chips on smartphones running Android P. The process fails during the connecting to the chip in the DiscoverDeviceActivity. From logs I was able to pinpoint where is it failing. Seems like the `getNetworkForSSID(SSID ssid)` method in WifiFacade is returning `null` and therefore the `bindSocketToSoftAp(Socket socket)` in NetworkBindingSocketFactory throws `SocketBindingException("Could not find Network for SSID " + softAPSSID)`. I don't have a smartphone with Android P so I'm not able to test it right now. 

Here are all logs I have:
[particle-bug-log.txt](https://github.com/particle-iot/spark-setup-android/files/2446774/particle-bug-log.txt)

![particle-bug](https://user-images.githubusercontent.com/13890361/46481976-d7b96800-c7f4-11e8-8839-845211669069.png)

**Comment by jensck** [comment]
Your timing is perfect: I believe I've fixed this and I'll be releasing an update to the device setup lib shortly.

Thanks for the awesomely detailed report!  I'll close this bug when the release is out.

**Comment by jensck** [comment]
Thanks for your patience waiting for the release.  An update with the fix has been pushed as version `0.6.1`.

**Comment by rduriancik** [comment]
Thank you very much. :ok_hand:
