### ISSUE TITLE
On setup choosing WiFi and going back, need to disconnect from Photon Soft AP

### ISSUE THREAD

**Issue by bloukingfisher** [particle-iot/spark-setup-android#68]
Issue: When user changes mind about WiFi network, the phone remains connected to Soft AP and fails when selecting "Ready". (Not tested, but leaving the app they may still remain connected to Soft AP thus failing any other internet connection they are expecting to have if setup was abandoned.)

To reproduce issue: Setup > "Ready" > Select Photon Soft AP > See list of WiFi networks...user changes mind and goes "Back" via Android back buton (user for example decides maybe they needed to select a different Photon Soft AP, or going back while walking in range to a different WiFi network).

Back on the Ready screen, when hitting Ready to setup again it fails to advance. At this point the device is still connected to the Soft AP. If the user manually changes back their WiFi connection, only then will Ready work again.

**Comment by jensck** [comment]
Moved here: https://github.com/particle-iot/particle-android/issues/56
